//! `trybuild`-driven compile-fail tests for the typed `Edge::new_*`
//! constructors.
//!
//! Proves that wrong-pair endpoint IDs (see ADR-0015 + commitment ledger
//! row C15) are rejected at compile time. Each fixture under
//! `edge_type_safety/compile_fail/` is a minimal `.rs` program that the
//! Rust compiler must reject; `trybuild` also checks the error message
//! matches the `.stderr` file next to it.
//!
//! The pair of files per case:
//!
//! ```text
//! edge_type_safety/compile_fail/
//!     ├── <case>.rs        — the code that must NOT compile
//!     └── <case>.stderr    — the expected compiler error (first snapshot
//!                            is generated by trybuild on first run and
//!                            must be committed)
//! ```
//!
//! If the Rust compiler changes its exact wording, run
//! `TRYBUILD=overwrite cargo test -p domain --test edge_type_safety`
//! locally to regenerate the snapshots, review the diff, commit.

#[test]
fn compile_fail_fixtures() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/edge_type_safety/compile_fail/*.rs");
}
