//! Property tests for [`domain::templates::a::fire_grant_on_lead_assignment`].
//!
//! Commitment-ledger row **C7** calls for proptest-pinned invariants on
//! the Grant shape — M4/P3's `TemplateAFireListener` will invoke this
//! pure-fn on every `HAS_LEAD` edge write, so a single shape regression
//! would silently poison production grants until an operator noticed.
//! The invariants below mirror the deliverable tags in the M4 plan
//! §Template A firing (s05) — if any of them drifts, the proptest
//! trips in < 50 cases.
//!
//! Invariants pinned (50 proptest cases):
//! 1. `holder == Agent(args.lead)`.
//! 2. `action == ["read", "inspect", "list"]` (stable order).
//! 3. `resource.uri == "project:<project-uuid>"`.
//! 4. `descends_from == Some(args.adoption_auth_request_id)`.
//! 5. `delegable == false`.
//! 6. `fundamentals == [Tag]`.
//! 7. `revoked_at.is_none()`.
//! 8. Distinct `GrantId` across independent calls.

use chrono::{DateTime, TimeZone, Utc};
use domain::model::ids::{AgentId, AuthRequestId, ProjectId};
use domain::model::{Fundamental, PrincipalRef};
use domain::templates::a::{fire_grant_on_lead_assignment, FireArgs};
use proptest::prelude::*;

// ---- Arbitrary generators --------------------------------------------------
//
// UUIDs are generated by `*::new()` (the `Id` newtype wraps `Uuid::new_v4()`)
// so proptest shrinking gives the same value on re-run; `now` varies over
// a 20-year window so the timestamp invariant isn't trivially satisfied
// by always using `Utc::now()`.

fn arb_now() -> impl Strategy<Value = DateTime<Utc>> {
    // 2020-01-01 .. 2040-01-01 in seconds.
    (1_577_836_800i64..2_208_988_800i64).prop_map(|s| Utc.timestamp_opt(s, 0).unwrap())
}

fn arb_args() -> impl Strategy<Value = FireArgs> {
    arb_now().prop_map(|now| FireArgs {
        project: ProjectId::new(),
        lead: AgentId::new(),
        adoption_auth_request_id: AuthRequestId::new(),
        now,
    })
}

// ---- Property tests --------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(50))]

    #[test]
    fn holder_is_the_supplied_lead(args in arb_args()) {
        let expected = args.lead;
        let g = fire_grant_on_lead_assignment(args);
        match g.holder {
            PrincipalRef::Agent(a) => prop_assert_eq!(a, expected),
            other => prop_assert!(
                false,
                "expected Agent holder, got {:?}",
                other
            ),
        }
    }

    #[test]
    fn action_is_read_inspect_list_in_stable_order(args in arb_args()) {
        let g = fire_grant_on_lead_assignment(args);
        prop_assert_eq!(g.action, vec!["read", "inspect", "list"]);
    }

    #[test]
    fn resource_uri_names_the_project_uuid(args in arb_args()) {
        let expected = format!("project:{}", args.project);
        let g = fire_grant_on_lead_assignment(args);
        prop_assert_eq!(g.resource.uri, expected);
    }

    #[test]
    fn descends_from_supplied_adoption_ar(args in arb_args()) {
        let expected = args.adoption_auth_request_id;
        let g = fire_grant_on_lead_assignment(args);
        prop_assert_eq!(g.descends_from, Some(expected));
    }

    #[test]
    fn grant_is_non_delegable_and_unrevoked(args in arb_args()) {
        let g = fire_grant_on_lead_assignment(args);
        prop_assert!(!g.delegable);
        prop_assert!(g.revoked_at.is_none());
    }

    #[test]
    fn fundamentals_list_is_exactly_tag(args in arb_args()) {
        let g = fire_grant_on_lead_assignment(args);
        prop_assert_eq!(g.fundamentals, vec![Fundamental::Tag]);
    }

    #[test]
    fn issued_at_matches_supplied_now(args in arb_args()) {
        let expected = args.now;
        let g = fire_grant_on_lead_assignment(args);
        prop_assert_eq!(g.issued_at, expected);
    }

    #[test]
    fn independent_calls_produce_distinct_grant_ids(a in arb_args(), b in arb_args()) {
        let ga = fire_grant_on_lead_assignment(a);
        let gb = fire_grant_on_lead_assignment(b);
        prop_assert_ne!(ga.id, gb.id);
    }
}
